// SPDX-FileCopyrightText: 2026 PuroSlavKing <puroslavking@yahoo.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Globalization;
using System.Linq;
using Content.Client.UserInterface.Screens;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    // Orion-Start
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ContentLocalizationManager _contentLoc = default!;
    // Orion-End

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };

        // Orion-Start
        PopulateLanguageDropDown();
        DropDownLanguage.Button.OnItemSelected += args =>
        {
            var cultureName = (string?) args.Button.GetItemMetadata(args.Id);
            if (cultureName == null || !_contentLoc.TrySetCulture(cultureName))
            {
                PopulateLanguageDropDown();
                return;
            }

            _cfg.SaveToFile();
        };
        // Orion-End

        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        Control.AddOptionCheckBox(CCVars.InterfaceChatFollowButton, ChatFollowButton);

        Control.Initialize();
    }

    // Orion-Start
    public void UpdateLocalizedText()
    {
        UiStyleLabel.Text = Loc.GetString("ui-options-general-ui-style");
        DropDownLanguage.Title = Loc.GetString("ui-options-language");
        DropDownHudTheme.Title = Loc.GetString("ui-options-hud-theme");
        DropDownHudLayout.Title = Loc.GetString("ui-options-hud-layout");
        PopulateLanguageDropDown();
    }

    private void PopulateLanguageDropDown()
    {
        var button = DropDownLanguage.Button;
        button.Clear();

        var cultures = _contentLoc.FoundCultures
            .OrderBy(culture => culture.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();
        for (var i = 0; i < cultures.Count; i++)
        {
            var culture = cultures[i];

            button.AddItem(culture.NativeName, i);
            button.SetItemMetadata(button.GetIdx(i), culture.Name);

            if (string.Equals(CultureInfo.CurrentUICulture.Name, culture.Name, StringComparison.OrdinalIgnoreCase))
                button.SelectId(i);
        }
    }
    // Orion-End
}
