// SPDX-FileCopyrightText: 2026 PuroSlavKing <puroslavking@yahoo.com>
// SPDX-FileCopyrightText: 2026 RedFoxIV <38788538+redfoxiv@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Lobby;
using Content.Orion.Shared.CustomGhost;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Orion.Client.CustomGhost.UI;

[GenerateTypedNameReferences]
public sealed partial class CustomGhostsWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private ISharedPlayerManager _player = default!;
    [Dependency] private IClientPreferencesManager _pref = default!;
    [Dependency] private IClientConsoleHost _conhost = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IEntitySystemManager _entSys = default!;

    private readonly SpriteSystem _sprite;
    private readonly List<EntityUid> _previewEntities = new();
    private readonly List<Control> _hidden = new();
    private readonly Dictionary<string, List<CustomGhostPrototype>> _allGhosts = new();
    private Button? _currentActive;
    private string _currentGhostProtoId;

    public CustomGhostsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entSys.GetEntitySystem<SpriteSystem>();

        _currentGhostProtoId = _pref.Preferences?.CustomGhost ?? "default";
        ShowAllCheckBox.OnToggled += ToggleVisibility;

        OnClose += () =>
        {
            foreach (var ent in _previewEntities)
            {
                _entMan.TryQueueDeleteEntity(ent);
            }

            _previewEntities.Clear();
        };

        BuildList();
    }

    private void BuildList()
    {
        var allGhostProtos = _proto.EnumeratePrototypes<CustomGhostPrototype>()
            .Where(proto => !proto.Abstract)
            .OrderBy(item => item.DisplayName);

        foreach (var ghostProto in allGhostProtos)
        {
            _allGhosts.GetOrNew(ghostProto.Category).Add(ghostProto);
        }

        var categories = _allGhosts.Keys.Order();
        foreach (var category in categories)
        {
            var label = AddCategoryLabel(category);
            var ghosts = _allGhosts[category];
            var buttons = new List<CustomGhostButton>();
            foreach (var ghostProto in ghosts)
            {
                if (AddButton(ghostProto) is { } button)
                    buttons.Add(button);
            }

            if (buttons.Count == 0)
            {
                ScrollBox.RemoveChild(label);
                continue;
            }

            if (buttons.Any(button => button.Visible))
                continue;

            label.Visible = false;
            _hidden.Add(label);
        }
    }

    private CustomGhostButton? AddButton(CustomGhostPrototype ghostProto)
    {
        if (_player.LocalSession is not { } session)
            return null;

        var available = ghostProto.CanUse(session, out var fullFailReason, out var canSee);
        if (!canSee)
            return null;

        var button = new CustomGhostButton();
        ScrollBox.AddChild(button);
        button.ActualButton.Name = ghostProto.ID;
        var ghostEnt = _entMan.Spawn(ghostProto.GhostEntityPrototype);
        _previewEntities.Add(ghostEnt);
        _sprite.ForceUpdate(ghostEnt);
        _sprite.SetVisible(ghostEnt, true);
        button.EntityTextureRects.SetEntity(ghostEnt);

        button.EntityLabel.Text = ghostProto.DisplayName;
        button.ActualButton.ToolTip = ghostProto.DisplayDesc;

        if (_currentGhostProtoId == ghostProto.ID)
        {
            button.ActualButton.Pressed = true;
            _currentActive = button.ActualButton;
        }

        button.ActualButton.OnPressed += OnPressed;

        if (available)
            return button;

        button.Modulate = Color.Red;
        button.Visible = false;
        button.ActualButton.Disabled = true;
        button.ActualButton.ToolTip += $"\n\n{Loc.GetString("custom-ghost-window-tooltip-to-unlock")}{fullFailReason}";
        _hidden.Add(button);
        return button;
    }

    private Label AddCategoryLabel(string text)
    {
        var label = new Label()
        {
            StyleClasses = { "FancyWindowTitle" },
        };

        label.Text = $"-- {Loc.GetString($"custom-ghost-category-{text}")} --";
        ScrollBox.AddChild(label);
        return label;
    }

    private void OnPressed(BaseButton.ButtonEventArgs args)
    {
        var protoId = args.Button.Name!;
        if (protoId == _currentGhostProtoId)
        {
            args.Button.Pressed = true;
            return;
        }

        _currentActive?.Pressed = false;

        _currentGhostProtoId = protoId;
        _currentActive = (Button) args.Button;
        _pref.SetCustomGhost(protoId);
        _conhost.ExecuteCommand($"setcustomghost {CommandParsing.Escape(protoId)}");
    }

    private void ToggleVisibility(BaseButton.ButtonToggledEventArgs args)
    {
        foreach (var button in _hidden)
        {
            button.Visible = args.Pressed;
        }
    }

    public sealed class CustomGhostButton : Control
    {
        public Button ActualButton { get; }
        public Label EntityLabel { get; }
        public SpriteView EntityTextureRects { get; }

        public CustomGhostButton()
        {
            AddChild(ActualButton = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
            });

            AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
            {
                (EntityTextureRects = new SpriteView
                {
                    SetSize = new Vector2(32, 32),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    Stretch = SpriteView.StretchMode.Fill,
                }),

                (EntityLabel = new Label
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalExpand = true,
                    Text = "sp00ky",
                    ClipText = true,
                }),
            },
            });
        }
    }
}
