# SPDX-FileCopyrightText: 2026 ReWAFFlution <rockstarfly65@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: true
contact_links:
  - name: Вопросы?
    url: https://github.com/ReWAFFlution
    about: Все вопросы можно задать в личные сообщения по дискорду rewafflution .
