// SPDX-FileCopyrightText: 2026 _kote <143940725+le-kote@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 PuroSlavKing <puroslavking@yahoo.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.Lobby.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.Rotting;
using Content.Shared.Body;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.EntityConditions.Conditions.Body;
using Content.Shared.EntityEffects;
using Content.Shared.EntityEffects.Effects.Body;
using Content.Shared.Metabolism;
using Content.Shared.Movement.Components;
using Content.Shared.Movement.Pulling.Components;
using Content.Shared.Nutrition.Components;
using Content.Shared.Roles;
using Content.Shared.Sericulture;
using Content.Shared.Storage;
using Content.Shared.Temperature.Components;
using Content.Shared.Traits.Assorted;
using Robust.Shared.GameObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Orion.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    // All differences are relative to BaselineSpecies
    private const string BaselineSpecies = "Human";
    private const string RespirationMetabolismType = "Respiration";
    private const float DamageDifferenceEpsilon = 0.005f;

    private readonly DocumentParsingManager _parsingMan;
    private string _currentSpecies;
    private readonly HumanoidCharacterProfile _profile;
    private readonly IPrototypeManager _proto;
    private readonly IResourceManager _resMan;
    private readonly IComponentFactory _componentFactory;

    public SpeciesWindow(SpeciesWindowContext context)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var context1 = context;
        _profile = context.Profile;
        _currentSpecies = _profile.Species;

        Select.OnPressed += _ => context1.OnChosen(_currentSpecies);

        Title = Loc.GetString("species-window-title");
        _proto = context.PrototypeManager;
        _resMan = context.ResourceManager;
        _parsingMan = context.ParsingManager;
        _componentFactory = IoCManager.Resolve<IComponentFactory>();
        OnClose += context.OnClosed;

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.Sort((x, y) => string.Compare(Loc.GetString(x.Name), Loc.GetString(y.Name), StringComparison.CurrentCulture));

        AddSpeciesCategory("species-category-label-classic", SpeciesCategory.Classic, protoList);
        AddSpeciesCategory("species-category-label-unusual", SpeciesCategory.Unusual, protoList);
        AddSpeciesCategory("species-category-label-special", SpeciesCategory.Special, protoList);
        AddSpeciesCategory("species-category-label-sponsor", SpeciesCategory.Sponsor, protoList);

        SelectSpecies(_profile.Species);
    }

    private void AddSpeciesCategory(string labelKey, SpeciesCategory category, IEnumerable<SpeciesPrototype> prototypes)
    {
        var categoryPrototypes = prototypes.Where(x => x.Category == category).ToList();
        if (categoryPrototypes.Count == 0)
            return;

        AddLabel(Loc.GetString(labelKey));

        foreach (var item in categoryPrototypes)
        {
            var button = new SpeciesButton(item.ID)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args =>
            {
                if (!args.Pressed)
                    return;

                SelectSpecies(item.ID);
            };

            SpeciesContainer.AddChild(button);
        }
    }

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };

        var label = new Label()
        {
            Text = text,
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
            HorizontalAlignment = HAlignment.Center,
        };

        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };

        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    private void SelectSpecies(string protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;

            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index<SpeciesPrototype>(protoId);
        _currentSpecies = protoId;

        JobPrototype? jobProto = null;
        var highJob = _profile.JobPriorities.FirstOrDefault(x => x.Value == JobPriority.High);
        if (!string.IsNullOrEmpty(highJob.Key) && _proto.TryIndex(highJob.Key, out var job))
            jobProto = job;

        var previewProfile = _profile;
        previewProfile = previewProfile.WithSpecies(protoId);

        var strategy = _proto.Index(proto.SkinColoration).Strategy;
        previewProfile = previewProfile.WithCharacterAppearance(
            HumanoidCharacterAppearance.EnsureValid(
                previewProfile.Appearance.WithSkinColor(strategy.ClosestSkinColor(_profile.Appearance.SkinColor)),
                protoId,
                previewProfile.Sex));

        Mob.LoadPreview(previewProfile, jobProto, false);
        JobLoadout.LoadPreview(previewProfile, jobProto);

        Select.Disabled = _profile.Species == protoId;

        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };

        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
        };

        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };

        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        var generatedEntries = BuildGeneratedProsCons(proto);
        generatedEntries.Sort((x, y) => y.IsPositive.CompareTo(x.IsPositive));
        if (generatedEntries.Count == 0)
        {
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
            };

            prosConsContainer.AddChild(noProsConsLabel);
        }
        else
        {
            foreach (var entry in generatedEntries)
            {
                var label = new RichTextLabel()
                {
                    Text = entry.Text,
                    StyleClasses = { StyleClass.LowDivider },
                    Margin = new(4f, 2f),
                };

                prosConsContainer.AddChild(label);
            }

            prosConsContainer.AddChild(new Control() { MinHeight = 8f });
        }

        if (!proto.Description.HasValue)
            return;

        // Take race descriptions text from .xml files, so we need to find and use the content from the specified file.
        // Everything works the same way as in the guidebook (yes, you can insert images here)
        if (!_resMan.TryContentFileRead(proto.Description.Value, out var file))
            return;

        using (file)
        using (var reader = new StreamReader(file))
        {
            _parsingMan.TryAddMarkup(DetailInfoContainer, reader.ReadToEnd());
        }
    }

    private List<SpeciesProsConsEntry> BuildGeneratedProsCons(SpeciesPrototype species)
    {
        var entries = new List<SpeciesProsConsEntry>();

        if (!_proto.Resolve<SpeciesPrototype>(BaselineSpecies, out var baselineSpecies) || !_proto.TryIndex(species.Prototype, out var speciesEntity) || !_proto.TryIndex(baselineSpecies.Prototype, out var baselineEntity))
            return entries;

        AddDamageModifierEntries(entries, speciesEntity, baselineEntity);
        AddDamageOverTimeEntries(entries, speciesEntity, baselineEntity);
        AddMetabolismEntries(entries, speciesEntity, baselineEntity);
        AddMobilityEntries(entries, speciesEntity, baselineEntity);
        AddStaminaEntries(entries, speciesEntity, baselineEntity);
        AddMetabolizerTypeEntries(entries, speciesEntity, baselineEntity);
        AddBreathGasEntries(entries, speciesEntity, baselineEntity);
        AddTemperatureEntries(entries, speciesEntity, baselineEntity);
        AddComponentPresenceEntries(entries, speciesEntity, baselineEntity);
        AddFlammableEntries(entries, speciesEntity, baselineEntity);
        AddCloneabilityEntry(entries, speciesEntity, baselineEntity);

        return entries;
    }

    private void AddDamageModifierEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        var speciesModifiers = GetDamageModifiers(speciesEntity);
        var baselineModifiers = GetDamageModifiers(baselineEntity);
        var groupedDamageTypes = new Dictionary<(bool IsPositive, float Percent), List<string>>();
        var damageTypes = speciesModifiers.Coefficients.Keys
            .Concat(baselineModifiers.Coefficients.Keys)
            .Distinct(StringComparer.Ordinal);

        foreach (var damageType in damageTypes)
        {
            var speciesCoefficient = GetDamageCoefficient(speciesModifiers, damageType);
            var baselineCoefficient = GetDamageCoefficient(baselineModifiers, damageType);
            var ratio = speciesCoefficient / baselineCoefficient;

            if (MathF.Abs(ratio - 1f) < DamageDifferenceEpsilon)
                continue;

            var percent = MathF.Round(MathF.Abs(ratio - 1f) * 100f);
            if (percent <= 0f)
                continue;

            var key = (ratio < 1f, percent);
            if (!groupedDamageTypes.TryGetValue(key, out var group))
            {
                group = new List<string>();
                groupedDamageTypes.Add(key, group);
            }

            group.Add(LocDamageTypeName(damageType));
        }

        foreach (var ((isPositive, percent), damageTypesGroup) in groupedDamageTypes.OrderByDescending(x => x.Key.IsPositive).ThenByDescending(x => x.Key.Percent))
        {
            var locKey = isPositive
                ? "ui-species-generated-damage-resistant"
                : "ui-species-generated-damage-vulnerable";

            entries.Add(new SpeciesProsConsEntry(
                isPositive,
                Loc.GetString(locKey,
                    ("percent", percent),
                    ("damage", FormatLocalizedList(damageTypesGroup)))));
        }
    }

    private DamageModifierSet GetDamageModifiers(EntityPrototype entity)
    {
        if (!TryGetPrototypeComponent<DamageableComponent>(entity, out var damageable) || damageable.DamageModifierSetId == null || !_proto.Resolve(damageable.DamageModifierSetId, out var modifiers))
            return new DamageModifierSet();

        return modifiers;
    }

    private static float GetDamageCoefficient(DamageModifierSet modifiers, string damageType)
    {
        return modifiers.Coefficients.GetValueOrDefault(damageType, 1f);
    }

    private void AddDamageOverTimeEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        AddDamageSpecifierDifference(entries,
            TryGetPrototypeComponent<PassiveDamageComponent>(speciesEntity, out var speciesPassive) ? speciesPassive.Damage : new DamageSpecifier(),
            TryGetPrototypeComponent<PassiveDamageComponent>(baselineEntity, out var baselinePassive) ? baselinePassive.Damage : new DamageSpecifier(),
            "ui-species-generated-passive-damage-more",
            "ui-species-generated-passive-damage-less");

        AddDamageSpecifierDifference(entries,
            TryGetPrototypeComponent<FlammableComponent>(speciesEntity, out var speciesFlammable) ? speciesFlammable.Damage : new DamageSpecifier(),
            TryGetPrototypeComponent<FlammableComponent>(baselineEntity, out var baselineFlammable) ? baselineFlammable.Damage : new DamageSpecifier(),
            "ui-species-generated-burning-damage-more",
            "ui-species-generated-burning-damage-less");
    }

    private void AddMetabolismEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        if (TryGetPrototypeComponent<HungerComponent>(speciesEntity, out var speciesHunger) && TryGetPrototypeComponent<HungerComponent>(baselineEntity, out var baselineHunger))
        {
            AddRateDifference(entries,
                speciesHunger.BaseDecayRate,
                baselineHunger.BaseDecayRate,
                "ui-species-generated-hunger-faster",
                "ui-species-generated-hunger-slower");
        }

        if (TryGetPrototypeComponent<ThirstComponent>(speciesEntity, out var speciesThirst) && TryGetPrototypeComponent<ThirstComponent>(baselineEntity, out var baselineThirst))
        {
            AddRateDifference(entries,
                speciesThirst.BaseDecayRate,
                baselineThirst.BaseDecayRate,
                "ui-species-generated-thirst-faster",
                "ui-species-generated-thirst-slower");
        }
    }

    private void AddMobilityEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        var speciesMovement = TryGetPrototypeComponent<MovementSpeedModifierComponent>(speciesEntity, out var movement)
            ? movement
            : new MovementSpeedModifierComponent();
        var baselineMovement = TryGetPrototypeComponent<MovementSpeedModifierComponent>(baselineEntity, out movement)
            ? movement
            : new MovementSpeedModifierComponent();

        AddRateDifference(entries,
            speciesMovement.BaseWalkSpeed,
            baselineMovement.BaseWalkSpeed,
            "ui-species-generated-walk-speed-faster",
            "ui-species-generated-walk-speed-slower");
        AddRateDifference(entries,
            speciesMovement.BaseSprintSpeed,
            baselineMovement.BaseSprintSpeed,
            "ui-species-generated-sprint-speed-faster",
            "ui-species-generated-sprint-speed-slower");
    }

    private void AddStaminaEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        var speciesStamina = TryGetPrototypeComponent<StaminaComponent>(speciesEntity, out var stamina)
            ? stamina
            : new StaminaComponent();
        var baselineStamina = TryGetPrototypeComponent<StaminaComponent>(baselineEntity, out stamina)
            ? stamina
            : new StaminaComponent();

        AddThresholdDifference(entries,
            speciesStamina.BaseCritThreshold,
            baselineStamina.BaseCritThreshold,
            "ui-species-generated-stamina-threshold-higher",
            "ui-species-generated-stamina-threshold-lower",
            MathF.Round(speciesStamina.BaseCritThreshold),
            "stamina");
    }

    private void AddMetabolizerTypeEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        var speciesTypes = GetMetabolizerTypes(speciesEntity);
        var baselineTypes = GetMetabolizerTypes(baselineEntity);

        foreach (var type in speciesTypes.Except(baselineTypes).Order())
        {
            entries.Add(new SpeciesProsConsEntry(true,
                Loc.GetString("ui-species-generated-metabolizer-type", ("type", LocMetabolizerTypeName(type)))));
        }
    }

    private void AddBreathGasEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        var speciesGases = GetBreathableGasReagents(GetMetabolizerTypes(speciesEntity));
        var baselineGases = GetBreathableGasReagents(GetMetabolizerTypes(baselineEntity));

        var addedGases = speciesGases.Except(baselineGases).Select(LocReagentName).ToList();
        if (addedGases.Count > 0)
        {
            entries.Add(new SpeciesProsConsEntry(true,
                Loc.GetString("ui-species-generated-breathes-gas", ("gas", FormatLocalizedList(addedGases)))));
        }

        var removedGases = baselineGases.Except(speciesGases).Select(LocReagentName).ToList();
        if (removedGases.Count > 0)
        {
            entries.Add(new SpeciesProsConsEntry(false,
                Loc.GetString("ui-species-generated-does-not-breathe-gas", ("gas", FormatLocalizedList(removedGases)))));
        }
    }

    private void AddTemperatureEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        if (!TryGetPrototypeComponent<TemperatureDamageComponent>(speciesEntity, out var speciesTemperature) || !TryGetPrototypeComponent<TemperatureDamageComponent>(baselineEntity, out var baselineTemperature))
            return;

        AddThresholdDifference(entries,
            speciesTemperature.HeatDamageThreshold,
            baselineTemperature.HeatDamageThreshold,
            "ui-species-generated-heat-threshold-higher",
            "ui-species-generated-heat-threshold-lower");
        AddThresholdDifference(entries,
            speciesTemperature.ColdDamageThreshold,
            baselineTemperature.ColdDamageThreshold,
            "ui-species-generated-cold-threshold-higher",
            "ui-species-generated-cold-threshold-lower");

        AddDamageSpecifierDifference(entries,
            speciesTemperature.HeatDamage,
            baselineTemperature.HeatDamage,
            "ui-species-generated-overheat-damage-more",
            "ui-species-generated-overheat-damage-less");
        AddDamageSpecifierDifference(entries,
            speciesTemperature.ColdDamage,
            baselineTemperature.ColdDamage,
            "ui-species-generated-cold-damage-more",
            "ui-species-generated-cold-damage-less");
    }

    private void AddComponentPresenceEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        AddMissingBaselineComponentEntry<PerishableComponent>(entries,
            speciesEntity,
            baselineEntity,
            "ui-species-generated-no-rotting");
        AddExtraComponentEntry<StorageComponent>(entries,
            speciesEntity,
            baselineEntity,
            "ui-species-generated-internal-storage");
        AddExtraComponentEntry<JumpAbilityComponent>(entries,
            speciesEntity,
            baselineEntity,
            "ui-species-generated-jump-ability");
        AddSericultureEntry(entries, speciesEntity, baselineEntity);

        if (TryGetPrototypeComponent<PullerComponent>(speciesEntity, out var speciesPuller) && TryGetPrototypeComponent<PullerComponent>(baselineEntity, out var baselinePuller) && speciesPuller.NeedsHands != baselinePuller.NeedsHands)
        {
            entries.Add(new SpeciesProsConsEntry(!speciesPuller.NeedsHands,
                Loc.GetString(speciesPuller.NeedsHands
                    ? "ui-species-generated-pulling-needs-hands"
                    : "ui-species-generated-pulling-without-hands")));
        }
    }

    private void AddSericultureEntry(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        if (!TryGetPrototypeComponent<SericultureComponent>(speciesEntity, out _) || TryGetPrototypeComponent<SericultureComponent>(baselineEntity, out _))
            return;

        entries.Add(new SpeciesProsConsEntry(true, Loc.GetString("ui-species-generated-sericulture")));
    }

    private void AddFlammableEntries(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        if (!TryGetPrototypeComponent<FlammableComponent>(speciesEntity, out var speciesFlammable) || !TryGetPrototypeComponent<FlammableComponent>(baselineEntity, out var baselineFlammable))
            return;

        AddRateDifference(entries,
            speciesFlammable.FirestacksOnIgnite,
            baselineFlammable.FirestacksOnIgnite,
            "ui-species-generated-ignites-easier",
            "ui-species-generated-ignites-harder");
    }

    private void AddCloneabilityEntry(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity)
    {
        var speciesCloneable = IsCloneable(speciesEntity);
        var baselineCloneable = IsCloneable(baselineEntity);

        if (speciesCloneable == baselineCloneable)
            return;

        entries.Add(new SpeciesProsConsEntry(
            speciesCloneable,
            Loc.GetString(speciesCloneable
                ? "ui-species-generated-cloneable"
                : "ui-species-generated-uncloneable")));
    }

    private bool IsCloneable(EntityPrototype entity)
    {
        return !TryGetPrototypeComponent<UnrevivableComponent>(entity, out var unrevivable) || unrevivable.Cloneable;
    }

    private void AddDamageSpecifierDifference(List<SpeciesProsConsEntry> entries, DamageSpecifier speciesDamage, DamageSpecifier baselineDamage, string moreKey, string lessKey)
    {
        var groupedDamageTypes = new Dictionary<(bool IsPositive, FixedPoint2 Amount), List<string>>();
        var damageTypes = speciesDamage.DamageDict.Keys
            .Select(type => type.Id)
            .Concat(baselineDamage.DamageDict.Keys.Select(type => type.Id))
            .Distinct(StringComparer.Ordinal);

        foreach (var damageType in damageTypes)
        {
            var species = GetDamageAmount(speciesDamage, damageType);
            var baseline = GetDamageAmount(baselineDamage, damageType);
            var difference = species - baseline;
            if (difference == FixedPoint2.Zero)
                continue;

            var key = (difference < FixedPoint2.Zero, Abs(difference));
            if (!groupedDamageTypes.TryGetValue(key, out var group))
            {
                group = new List<string>();
                groupedDamageTypes.Add(key, group);
            }

            group.Add(LocDamageTypeName(damageType));
        }

        foreach (var ((isPositive, amount), damageTypesGroup) in groupedDamageTypes.OrderByDescending(x => x.Key.IsPositive).ThenByDescending(x => x.Key.Amount))
        {
            entries.Add(new SpeciesProsConsEntry(isPositive,
                Loc.GetString(isPositive ? lessKey : moreKey,
                    ("damage", FormatLocalizedList(damageTypesGroup)),
                    ("amount", FormatFixedPoint(amount)))));
        }
    }

    private static FixedPoint2 GetDamageAmount(DamageSpecifier damage, string damageType)
    {
        return damage.DamageDict.GetValueOrDefault(damageType, FixedPoint2.Zero);
    }

    private static void AddRateDifference(List<SpeciesProsConsEntry> entries, float speciesRate, float baselineRate, string fasterKey, string slowerKey)
    {
        var ratio = speciesRate / baselineRate;
        if (MathF.Abs(ratio - 1f) < DamageDifferenceEpsilon)
            return;

        var percent = MathF.Round(MathF.Abs(ratio - 1f) * 100f);
        if (percent <= 0f)
            return;

        entries.Add(new SpeciesProsConsEntry(ratio < 1f, Loc.GetString(ratio > 1f ? fasterKey : slowerKey, ("percent", percent))));
    }

    private static void AddThresholdDifference(List<SpeciesProsConsEntry> entries, float speciesThreshold, float baselineThreshold, string higherKey, string lowerKey)
    {
        AddThresholdDifference(entries,
            speciesThreshold,
            baselineThreshold,
            higherKey,
            lowerKey,
            MathF.Round(speciesThreshold - 273.15f),
            "temperature");
    }

    private static void AddThresholdDifference(List<SpeciesProsConsEntry> entries, float speciesThreshold, float baselineThreshold, string higherKey, string lowerKey, float displayedValue, string valueName)
    {
        if (MathF.Abs(speciesThreshold - baselineThreshold) < DamageDifferenceEpsilon)
            return;

        entries.Add(new SpeciesProsConsEntry(speciesThreshold > baselineThreshold,
            Loc.GetString(speciesThreshold > baselineThreshold
                    ? higherKey
                    : lowerKey,
                (valueName, displayedValue))));
    }

    private HashSet<string> GetMetabolizerTypes(EntityPrototype entity)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        if (!TryGetPrototypeComponent<InitialBodyComponent>(entity, out var initialBody))
            return result;

        foreach (var organId in initialBody.Organs.Values)
        {
            EntProtoId organPrototype = organId;
            if (!_proto.TryIndex(organPrototype, out var organ) || !TryGetPrototypeComponent<MetabolizerComponent>(organ, out var metabolizer) || metabolizer.MetabolizerTypes == null)
                continue;

            foreach (var type in metabolizer.MetabolizerTypes)
            {
                result.Add(type.Id);
            }
        }

        return result;
    }

    private HashSet<string> GetBreathableGasReagents(HashSet<string> metabolizerTypes)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        foreach (var reagent in _proto.EnumeratePrototypes<ReagentPrototype>())
        {
            if (reagent.Metabolisms?.Metabolisms.TryGetValue(RespirationMetabolismType, out var respiration) != true)
                continue;

            foreach (var effect in respiration?.Effects ?? Array.Empty<EntityEffect>())
            {
                if (effect is not Oxygenate || !EffectAppliesToMetabolizerTypes(effect, metabolizerTypes))
                    continue;

                result.Add(reagent.ID);
                break;
            }
        }

        return result;
    }

    private static bool EffectAppliesToMetabolizerTypes(EntityEffect effect, HashSet<string> metabolizerTypes)
    {
        if (effect.Conditions == null || effect.Conditions.Length == 0)
            return true;

        foreach (var condition in effect.Conditions)
        {
            if (condition is not MetabolizerTypeCondition metabolizerCondition)
                continue;

            var overlaps = metabolizerCondition.Type != null && metabolizerCondition.Type.Any(type => metabolizerTypes.Contains(type.Id));

            if (metabolizerCondition.Inverted ? !overlaps : overlaps)
                return true;
        }

        return false;
    }

    private static string FormatLocalizedList(List<string> values)
    {
        values.Sort(StringComparer.CurrentCulture);

        return values.Count switch
        {
            0 => string.Empty,
            1 => values[0],
            2 => Loc.GetString("ui-species-list-two", ("first", values[0]), ("second", values[1])),
            _ => Loc.GetString("ui-species-list-many",
                ("head", string.Join(", ", values.Take(values.Count - 1))),
                ("tail", values[^1])),
        };
    }

    private static FixedPoint2 Abs(FixedPoint2 value)
    {
        return value < FixedPoint2.Zero
            ? -value
            : value;
    }

    private static string FormatFixedPoint(FixedPoint2 value)
    {
        return value.ToString("0.##", null);
    }

    private void AddExtraComponentEntry<T>(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity, string locKey) where T : Component, new()
    {
        if (TryGetPrototypeComponent<T>(speciesEntity, out _) && !TryGetPrototypeComponent<T>(baselineEntity, out _))
            entries.Add(new SpeciesProsConsEntry(true, Loc.GetString(locKey)));
    }

    private void AddMissingBaselineComponentEntry<T>(List<SpeciesProsConsEntry> entries, EntityPrototype speciesEntity, EntityPrototype baselineEntity, string locKey) where T : Component, new()
    {
        if (!TryGetPrototypeComponent<T>(speciesEntity, out _) && TryGetPrototypeComponent<T>(baselineEntity, out _))
            entries.Add(new SpeciesProsConsEntry(true, Loc.GetString(locKey)));
    }

    private bool TryGetPrototypeComponent<T>(EntityPrototype entity, out T component) where T : Component, new()
    {
        var registration = _componentFactory.GetRegistration<T>();
        if (entity.Components.TryGetValue(registration.Name, out var componentRegistry) && componentRegistry.Component is T typedComponent)
        {
            component = typedComponent;
            return true;
        }

        component = default!;
        return false;
    }

    private string LocDamageTypeName(string damageType)
    {
        return _proto.Resolve<DamageTypePrototype>(damageType, out var damageTypeProto)
            ? damageTypeProto.LocalizedName
            : damageType;
    }

    private string LocMetabolizerTypeName(string type)
    {
        return _proto.Resolve<MetabolizerTypePrototype>(type, out var metabolizerType)
            ? metabolizerType.LocalizedName
            : type;
    }

    private string LocReagentName(string reagent)
    {
        return _proto.Resolve<ReagentPrototype>(reagent, out var reagentPrototype)
            ? reagentPrototype.LocalizedName
            : reagent;
    }

    private sealed record SpeciesProsConsEntry(bool IsPositive, string Description)
    {
        public string Text => IsPositive
            ? $"[color=#13f244]- {Description}[/color]"
            : $"[color=#d63636]- {Description}[/color]";
    }

    private sealed class SpeciesButton(string proto) : Button
    {
        public readonly string Proto = proto;
    }
}
