# SPDX-FileCopyrightText: 2026 PuroSlavKing <puroslavking@yahoo.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CRLF Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
  merge_group:

jobs:
  build:
    name: CRLF Check
    if: ${{ github.event_name == 'merge_group' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Check for CRLF
      run: python Tools/check_crlf.py
